baseURL = "https://gowreesh-mago.github.io/hava-website/"
languageCode = "en"
title = "HAVA-Lab"
disableKinds = ["RSS"]

[params]
  description = "Human-Aligned Video AI Laboratory - UvA Data Science Centre"
  ogImage = "/media/og-image.jpg"
  location = "University Library Singel, Amsterdam"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Mission"
    url = "/mission/"
    weight = 2
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 3
  [[menu.main]]
    name = "Publications & News"
    url = "/publications/"
    weight = 4


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
